spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/bookstockmanager?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

# Enable caching
cache:
  type: ehcache

server:
  port: 9095

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
   level:
     org:
       hibernate: DEBUG # DEBUG
       springframework:
         web: DEBUG # DEBUG
         jdbc:
           datasource: DEBUG # DEBUG

#debug: true