version: "3.9"
services:
  # Database for all services
  postgres:
    container_name: ms_postgresql
    image: postgres:17.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "6345:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4:8.14.0
    # image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin.pgadmin@localhost.ms
      - PGADMIN_DEFAULT_PASSWORD=ms_pgadmin_password
      - PGADMIN_CONFIG_SERVER_MODE=False
      - GUNICORN_CMD_ARGS=--timeout 120
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5080:80"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongodb
    # image: mongo:5.0.31-rc0-nanoserver-ltsc2022
    image: mongo
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27018:27017"
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: unless-stopped

  # This is the default settings for the mails server
  mail-dev:
    container_name: ms_mail_dev
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: