spring:
  application:
    name: User Manager Service
  config:
    import: optional:configserver:http://ms_config_server:8888
  cloud:
    config:
      enabled: true
      fail-fast: false
      uri: http://ms_config_server:8888
      retry:
        max-attempts: 30
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      request-connect-timeout: 5000
      request-read-timeout: 5000
    discovery:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6343/usermanager?currentSchema=bookstore}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      pool-name: UserManagerHikariPool
      validation-timeout: 10000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: bookstore
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token-expiration: 86400000 # 24 hours in milliseconds
      refresh-token-expiration: 604800000 # 7 days in milliseconds
      token-prefix: "Bearer "